version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - .data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: {}
